version: '3.8'
services:
  client:
    image: node:18
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./client
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"

  server:
    image: node:18
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./server
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"
